# Generated by Django 3.0.3 on 2020-02-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='likecount',
            field=models.IntegerField(default=0),
        ),
    ]
